language: ruby
sudo: false
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
env:
  -
  - ACTIVE_RECORD_VERSION=4.0.0
  - ACTIVE_RECORD_VERSION=4.1.0
  - ACTIVE_RECORD_VERSION=4.2.0
  - ACTIVE_RECORD_VERSION=5.0.0
matrix:
  allow_failures:
    - rvm: 2.4
      env: ACTIVE_RECORD_VERSION=4.0.0
    - rvm: 2.4
      env: ACTIVE_RECORD_VERSION=4.1.0
cache: bundler
before_install:
  - gem update --system
  - gem --version
  - gem update bundle
  - bundle --version
script:
  - 'bundle exec rake'
notifications:
  email: false
